// Code generated by github.com/ssoor/gex. DO NOT EDIT.

// +build tools

package tools

// tool dependencies
import (
	_ "github.com/ssoor/gex/cmd/gex" // Global Tools
	_ "github.com/go-bindata/go-bindata/go-bindata"
)

// If you want to use tools, please run the following command:
//  go generate ./tools.go
//
//go:generate go get -v github.com/ssoor/gex/cmd/gex
//go:generate go build -v -o=./bin/go-bindata github.com/go-bindata/go-bindata/go-bindata
